export const SET_PARTITIONS = 'SET_PARTITIONS';
export const SET_QUERIES = 'SET_QUERIES';
export const SET_INPUT = 'SET_INPUT';
export const TOGGLE_CONFIG_MODAL = 'TOGGLE_CONFIG_MODAL';
export const SET_HOST_URL = 'SET_HOST_URL';
export const SET_HOST_URL_LOADING = 'SET_HOST_URL_LOADING';
